### ISSUE TITLE
kbst local shell causes destroy, not shell

### ISSUE THREAD

**Issue by jeacott1** [kbst/kbst#16]
```
>kbst local shell 
```
expected - connect to a local container.
actual - "Destroy complete! Resources: 19 destroyed."

**Comment by pst** [comment]
Thanks for reporting, the shell command was a copy and paste error when experimenting with the shell command by starting from the destroy command. Unfortunately this made it into a release.

I published a new release with this and numerous other improvements. https://github.com/kbst/kbst/releases/tag/v0.1.3
