### ISSUE TITLE
CLI Seems to break with Editors Cache File

### ISSUE THREAD

**Issue by Spazzy757** [kbst/kbst#6]
## Problem
I am currently using EMACS, when I edit the config a cache file is created
i.e. If I edit `config.auto.tfvars` it will create a cache file called `.#config.auto.tfvars`. This file will stay until I have saved the changes that I have made. Due to this behaviour if the CLI is running in watch mode and I edit a file it will trigger the rebuild and fail:

## Screenshot
![image](https://user-images.githubusercontent.com/19777480/94594821-41589980-028a-11eb-9260-8bb6ac7b8ea4.png)

**Comment by pst** [comment]
I looked into this. It's not an issue with `kbst` per se. It's the docker build failing, when it tries to copy Emacs' temp-symlink-file construct. I think the easiest way to fix this is to create a `.dockerignore` with content like below.

```
# Ignore Emacs temp files
.#*
\#*\#

```
